/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import map_application.RecordPointLayer;
import map_application.connect;

/**
 *
 * @author madha
 */
public class WestPanel extends javax.swing.JPanel {
    
    private Connection  conn;
    private ResultSet rs;
    private String name;
    private String District = "";
    private String Sch1 = "";
    private String Sch2 = "";
    private String Category = "";
    private String query = "";
    private RecordPointLayer newLayer;
    private Color color;

    /**
     * Creates new form WestPanel
     */
    public WestPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        district = new javax.swing.JComboBox<>();
        sch_type1 = new javax.swing.JComboBox<>();
        sch_type2 = new javax.swing.JComboBox<>();
        category = new javax.swing.JComboBox<>();
        Add_another = new javax.swing.JButton();
        layer_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        colorBox = new javax.swing.JComboBox<>();

        district.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Districts" }));

        sch_type1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Schools" }));

        sch_type2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Schools" }));

        category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Categories" }));

        Add_another.setText("ADD Layer");
        Add_another.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_anotherActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(56, 55, 54));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Layer Name");

        colorBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "black", "blue", "cyan", "dark_gray", "gray", "light_gray", "green", "magenta", "orange", "pink", "red", "white", "yellow", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(colorBox, 0, 139, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(layer_name)
                        .addComponent(Add_another, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                        .addComponent(district, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sch_type1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sch_type2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(category, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(district, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(sch_type1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(sch_type2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(colorBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(layer_name, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Add_another)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Add_anotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_anotherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Add_anotherActionPerformed

    public JButton getAdd_another() {
        return Add_another;
    }

    public void setAdd_another(JButton Add_another) {
        this.Add_another = Add_another;
    }

    public RecordPointLayer getNewLayer() {
        newLayer = new RecordPointLayer();
        name = layer_name.getText();
        
        if(colorBox.getSelectedItem() == "black"){
            color = Color.BLACK;
        }else if(colorBox.getSelectedItem() == "blue"){
            color = Color.BLUE;
        }else if(colorBox.getSelectedItem() == "cyan"){
            color = Color.CYAN;
        }else if(colorBox.getSelectedItem() == "dark_gray"){
            color = Color.DARK_GRAY;
        }else if(colorBox.getSelectedItem() == "gray"){
            color = Color.GRAY;
        }else if(colorBox.getSelectedItem() == "light_gray"){
            color = Color.LIGHT_GRAY;
        }else if(colorBox.getSelectedItem() == "green"){
            color = Color.GREEN;
        }else if(colorBox.getSelectedItem() == "magenta"){
            color = Color.MAGENTA;
        }else if(colorBox.getSelectedItem() == "orange"){
            color = Color.ORANGE;
        }else if(colorBox.getSelectedItem() == "pink"){
            color = Color.PINK;
        }else if(colorBox.getSelectedItem() == "red"){
            color = Color.RED;
        }else if(colorBox.getSelectedItem() == "white"){
            color = Color.WHITE;
        }else if(colorBox.getSelectedItem() == "yellow"){
            color = Color.YELLOW;
        }
        
        if(district.getSelectedItem().toString() != "All Districts"){
            District = "District = '"+district.getSelectedItem().toString()+"'";
        }
        if(sch_type1.getSelectedItem().toString() != "All Schools"){
            if(District != ""){
                Sch1 = " AND Sch_Type_Boy_Girls = '"+sch_type1.getSelectedItem().toString()+"'";
            }
            else{
                Sch1 = " Sch_Type_Boy_Girls = '"+sch_type1.getSelectedItem().toString()+"'";
            }
        }
        if(sch_type2.getSelectedItem().toString() != "All Schools"){
            if(District != "" || Sch1 != "" ){
                Sch2 = " AND SCH_Typ1 = '"+sch_type2.getSelectedItem().toString()+"'";
            }
            else{
                Sch2 = " SCH_Typ1 = '"+sch_type2.getSelectedItem().toString()+"'";
            }
        }
        if(category.getSelectedItem().toString() != "All Categories"){
            if(District != "" || Sch1 != "" || Sch2 != ""){
                Category = " AND Categogaryofcombinedscore = '"+category.getSelectedItem().toString()+"'";
            }
            else{
                Category = " Categogaryofcombinedscore = '"+category.getSelectedItem().toString()+"'";
            }
        }
        if(District != "" || Sch1 != "" || Sch2 != "" || Category != ""){
            query = "where";
        }

        newLayer.setName(name);
        try{
            conn = connect.ConnecterDb();
            rs = conn.createStatement().executeQuery("Select * from schools "+query+" "+District+" "+Sch1+" "+Sch2+" "+Category);
            while (rs.next()){
                newLayer.addRecordPoint(rs.getDouble(16), rs.getDouble(17), 4, rs.getString(6), color);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        return newLayer;
    }

    public void setNewLayer(RecordPointLayer newLayer) {
        this.newLayer = newLayer;
    }

    public JComboBox<String> getCategory() {
        return category;
    }

    public void setCategory(JComboBox<String> category) {
        this.category = category;
    }

    public JComboBox<String> getDistrict() {
        return district;
    }

    public void setDistrict(JComboBox<String> district) {
        this.district = district;
    }

    public JComboBox<String> getSch_type1() {
        return sch_type1;
    }

    public void setSch_type1(JComboBox<String> sch_type1) {
        this.sch_type1 = sch_type1;
    }

    public JComboBox<String> getSch_type2() {
        return sch_type2;
    }

    public void setSch_type2(JComboBox<String> sch_type2) {
        this.sch_type2 = sch_type2;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_another;
    private javax.swing.JComboBox<String> category;
    private javax.swing.JComboBox<String> colorBox;
    private javax.swing.JComboBox<String> district;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField layer_name;
    private javax.swing.JComboBox<String> sch_type1;
    private javax.swing.JComboBox<String> sch_type2;
    // End of variables declaration//GEN-END:variables
}
